<a href="https://colab.research.google.com/github/anurag25/pytorch-notebooks/blob/master/Deep%20Learning%20with%20PyTorch%20A%2060%20Minute%20Blitz/1_Copy_of_tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



# [My Block 0] Python's `__future__` Module


[Official Documentation](https://docs.python.org/3/reference/simple_stmts.html#future-statements): <br />
A future statement is a directive to the compiler that a particular module should be compiled using syntax or semantics that will be available in a specified future release of Python where the feature becomes standard.

The future statement is intended to ease migration to future versions of Python that introduce incompatible changes to the language. It allows use of the new features on a per-module basis before the release in which the feature becomes standard.

The only feature in Python 3.7 that requires using the future statement is `annotations`.

All historical features enabled by the future statement are still recognized by Python 3. The list includes `absolute_import, division`, `generators`, `generator_stop`, `unicode_literals`, `print_function`, `nested_scopes` and `with_statement`. They are all redundant because they are always enabled, and only kept for backwards compatibility.

In [0]:
import sys
print(sys.version)

3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0]


In [0]:
# [My Block 0 End]

In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [0]:
x = torch.empty(5, 3)
# A bolck of memory allocated for x which will contain uninitialized data
print(x)

tensor([[9.4715e-36, 0.0000e+00, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44],
        [1.5975e-43, 1.3593e-43, 1.5414e-43],
        [1.4013e-43, 1.5414e-43, 2.5591e-41],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [0]:
help(torch.empty)

Help on built-in function empty:

empty(...)
    empty(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False, pin_memory=False) -> Tensor
    
    Returns a tensor filled with uninitialized data. The shape of the tensor is
    defined by the variable argument :attr:`size`.
    
    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
            Default: if ``None``, uses the cur

In [0]:
torch.empty(2, 3)

tensor([[6.0359e-36, 0.0000e+00, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44]])

Construct a randomly initialized matrix:



In [0]:
help(torch.rand)

Help on built-in function rand:

rand(...)
    rand(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a tensor filled with random numbers from a uniform distribution
    on the interval :math:`[0, 1)`
    
    The shape of the tensor is defined by the variable argument :attr:`size`.
    
    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
    

In [0]:
x = torch.rand(4)
print(x)
print(x.shape)
print(type(x))

tensor([0.8825, 0.3960, 0.0035, 0.2524])
torch.Size([4])
<class 'torch.Tensor'>


In [0]:
x = torch.rand(5, 3)
# random numbers between [0, 1) from uniform distribution
print(x)
print(x.shape)
print(type(x))

tensor([[0.9853, 0.5394, 0.6494],
        [0.8340, 0.5207, 0.7737],
        [0.1691, 0.4988, 0.1855],
        [0.9557, 0.8262, 0.9122],
        [0.2325, 0.5099, 0.8710]])
torch.Size([5, 3])
<class 'torch.Tensor'>


Construct a matrix filled zeros and of dtype long:



In [0]:
torch.long

torch.int64

In [0]:
x = torch.zeros(5)
print(type(x))
print(x.type())
x

<class 'torch.Tensor'>
torch.FloatTensor


tensor([0., 0., 0., 0., 0.])

In [0]:
x = torch.zeros(5, 3, dtype=torch.long)
# torch.Tensor is an alias for the default tensor type (torch.FloatTensor)
# So if dtype not give, float tensor will be created. See the cell just above
print(type(x))
print(x.type())
print(x)

<class 'torch.Tensor'>
torch.LongTensor
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [0]:
# returns the current default tensor type
torch.get_default_dtype()

# Use torch.set_default_tensor_type(t) to set the default to type t

torch.float32

In [0]:
# numel: Returns the total number of elements in the input tensor.

print(torch.numel(torch.zeros(4,4)))
torch.zeros(4, 4)

16


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
# torch.tensor(data, dtype=None, device=None, requires_grad=False, pin_memory=False) → Tensor
# data (array_like) – Initial data for the tensor. Can be a list, tuple, NumPy ndarray, scalar, and other types.
# requires_grad (bool, optional) – If autograd should record operations on the returned tensor.
x = torch.tensor([5.5, 3])
print(type(x))
print(x.type())
print(x)
'''
torch.tensor() always copies data. 
If you have a Tensor data and want to avoid a copy, use torch.Tensor.requires_grad_() or torch.Tensor.detach(). 
If you have a NumPy ndarray and want to avoid a copy, use torch.as_tensor().
'''
print(x.size())
print(x.shape)

<class 'torch.Tensor'>
torch.FloatTensor
tensor([5.5000, 3.0000])
torch.Size([2])
torch.Size([2])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [5]:
x

tensor([5.5000, 3.0000])

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

# randn(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
#    Returns a tensor filled with random numbers from a normal distribution
#    with mean `0` and variance `1` (also called the standard normal
#    distribution).
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8103, -0.8533, -0.6301],
        [-0.7020, -0.5650, -0.4315],
        [-0.1037, -0.3360,  1.4869],
        [ 1.2886, -0.6033,  0.1010],
        [-2.0664, -1.2248, -1.9221]])


Get its size:



In [8]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.3244, -0.6619, -0.4794],
        [-0.2512, -0.0628,  0.2300],
        [ 0.0418,  0.4390,  2.0428],
        [ 1.9776,  0.2906,  0.9795],
        [-1.5978, -0.3911, -1.4398]])


Addition: syntax 2



In [11]:
help(torch.add)

Help on built-in function add:

add(...)
    .. function:: add(input, other, out=None)
    
    Adds the scalar :attr:`other` to each element of the input :attr:`input`
    and returns a new resulting tensor.
    
    .. math::
        \text{out} = \text{input} + \text{other}
    
    If :attr:`input` is of type FloatTensor or DoubleTensor, :attr:`other` must be
    a real number, otherwise it should be an integer.
    
    Args:
        input (Tensor): the input tensor.
        value (Number): the number to be added to each element of :attr:`input`
    
    Keyword arguments:
        out (Tensor, optional): the output tensor.
    
    Example::
    
        >>> a = torch.randn(4)
        >>> a
        tensor([ 0.0202,  1.0985,  1.3506, -0.6056])
        >>> torch.add(a, 20)
        tensor([ 20.0202,  21.0985,  21.3506,  19.3944])
    
    .. function:: add(input, other, *, alpha=1, out=None)
    
    Each element of the tensor :attr:`other` is multiplied by the scalar
    :attr:`alpha

In [0]:
'''
add(input, other, out=None)
    
    Adds the scalar :attr:`other` to each element of the input :attr:`input`
    and returns a new resulting tensor
'''

print(torch.add(x, y))

In [14]:
# add(input, other, *, alpha=1, out=None)
'''   
    Each element of the tensor :attr:`other` is multiplied by the scalar
    :attr:`alpha` and added to each element of the tensor :attr:`input`.
    The resulting tensor is returned.

'''
a = torch.rand(4)
print(a)
b = torch.randn(4)
print(b)
print(torch.add(a, b, alpha = 1000))
print(a + (b * 1000))

tensor([0.2023, 0.8727, 0.9498, 0.4153])
tensor([-1.0726, -0.9525,  0.7217, -0.7835])
tensor([-1072.3850,  -951.6572,   722.6768,  -783.0452])
tensor([-1072.3851,  -951.6572,   722.6768,  -783.0452])


Addition: providing an output tensor as argument



In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.3244, -0.6619, -0.4794],
        [-0.2512, -0.0628,  0.2300],
        [ 0.0418,  0.4390,  2.0428],
        [ 1.9776,  0.2906,  0.9795],
        [-1.5978, -0.3911, -1.4398]])


Addition: in-place



In [16]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.3244, -0.6619, -0.4794],
        [-0.2512, -0.0628,  0.2300],
        [ 0.0418,  0.4390,  2.0428],
        [ 1.9776,  0.2906,  0.9795],
        [-1.5978, -0.3911, -1.4398]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [17]:
print(x[:, 1])

tensor([-0.8533, -0.5650, -0.3360, -0.6033, -1.2248])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [18]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.9269])
1.9269232749938965


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!